### PR TITLE
Fix ethereum provider url

### LINKED ISSUE #142: Can't pass HTTPS node URL
**Description**

When running the connector, the `node_url` argument is expected to contain only the domain. Later, `http` is added in front, disabling to pass a full RPC node URL.

**Logs, Errors or Screenshots**

When I set it to **https://mainnet.infura.io/v3/**, the service won't start with message:
`Error: error sending request for url (http://https//mainnet.infura.io/v3/): error trying to connect: dns error: failed to lookup address information: Name does not resolve`

### PR DESCRIPTION
**Pull request by Lohann**
## Description

Fixes #142 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Code review prechecks:

- [x] Code follows the style guidelines of this project
- [x] Code has been self-reviewed
- [x] Inline comments have been added for each method
- [x] I have made corresponding changes to the documentation
- [x] Code changes introduces no new problems or warnings
- [x] Test cases have been added
- [x] Dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dvc94ch** [comment]
Pretty sure that breaks the tests and the docker compose. Really no other changes required?

**Comment by Lohann** [comment]
I'm investigating this right now, it depends if the `ethers::providers::Http` will infer the `http/https` or not.

**Comment by Lohann** [comment]
@dvc94ch  Yeah.. it doesn't infer the protocol, there's two ways to fix this:
1. Require the to provide the url schema in the `opts.node_addr` parameter and add a protocol paramter in the `BlockchainConfig` (because polkadot uses `ws` or `wss` connections).

2. On the ethereum-server, detect if the `opts.node_addr` is prefixed with a schema, if not prefix it with `http://`.

The first solution requires little more work, but in my opinion is better, because one node may expose multiples protocols (http, tpc, ws, wss, etc), so trying to infer the protocol may not work everywhere.

**Comment by dvc94ch** [comment]
What happens if we turn node address into node url? I think the reason we expect a socketaddr had something to do with ports and rosetta-docker

**Comment by Lohann** [comment]
>What happens if we turn node address into node url

Thinking... this may work if we provide the `host` to the `BlockchainClient::create_config` function, but this is tricky because the host can be internal (ip, localhost, etc), or public.. so the host may change depending from where you are calling the node (VPC? public? local?).

But the protocol parameter is the same regardless the host.

**Comment by dvc94ch** [comment]
Do what you think is best

File: rosetta-core/src/node_uri.rs [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+#[derive(Debug, Clone, PartialEq)]
+pub struct NodeUri<'a> {
+    pub scheme: &'a str,
+    pub userinfo: Option<&'a str>,
+    pub host: &'a str,
+    pub port: u16,
+    pub path: &'a str,
+    pub query: Option<&'a str>,
+    pub fragment: Option<&'a str>,
+}
```
Comment (Lohann) [inline rosetta-core/src/node_uri.rs:34]: I've created our own Uri wrapper, I could use one some one existing libraries like [http::uri](https://docs.rs/http/latest/http/uri/index.html) or [uriparse-rs](https://github.com/sgodwincs/uriparse-rs). But we have some extra requirements such as the `scheme` and `port` are mandatory, required for rosetta-docker. Also once this is a core struct, I think is better use our own struct, so we have more control in case of breaking changes.

I also decided to use [fluent-uri](https://github.com/yescallop/fluent-uri-rs) instead [uriparse-rs](https://github.com/sgodwincs/uriparse-rs) because fluent-uri have a better performance, is being actively maintained and support `no_std` environments.

File: chains/astar/server/src/lib.rs [hunk 2]
```diff
@@ -26,7 +26,14 @@ impl BlockchainClient for AstarClient {
...
     async fn new(config: BlockchainConfig, addr: &str) -> Result<Self> {
-        let client = EthereumClient::new(config, addr).await?;
+        // TODO: Fix this hack, need to support multiple addresses per node
+        let mut ethereum_rpc_uri = NodeUri::parse(addr)?;
+        ethereum_rpc_uri.scheme = if ethereum_rpc_uri.scheme == "ws" {
+            "http"
+        } else {
+            "https"
+        };
+        let client = EthereumClient::new(config, ethereum_rpc_uri.to_string().as_str()).await?;
```
Comment (Lohann) [inline chains/astar/server/src/lib.rs:36]: Astar requires both `ws` and `http` connections, using this dirty solution for now.

**Review by dvc94ch — APPROVED** [review]
Ok

**Review by penumbra23 — APPROVED** [review]
Tested on local, saw blocks being indexed, seems working!
